#!/usr/bin/make
# $Id: Makefile,v 1.1 2003/03/12 17:46:02 tramm Exp $

#
LIBS		=							\
	libgetoptions							\


#
# Option parsing library
#
libgetoptions.srcs	=						\
	getoptions.c							\

include ../Makefile.common

