#!/usr/bin/make
# $Id: Makefile.WIN32,v 1.1 2003/02/03 20:44:55 dennisda Exp $

MAKE		= make

all:									\
	srcdir								\

srcdir:
	$(MAKE) -C ./src

clean:
	$(MAKE) -C src clean
	-$(RM) -f core

depend:
	$(MAKE) -C src depend
