package net.sf.autopilot.downlink.uav;

import java.net.InetAddress;
import java.net.DatagramSocket;

/* Generated by Together */

public class UDPClientWatchdog extends Thread {
        final static int DATA_PORT = 12368;
        DatagramSocket udpSocket;

        public UDPClientWatchdog(DatagramSocket udpSocket) {
                this.udpSocket = udpSocket;
        }

        public void run() {
        }
}
