#!/usr/bin/perl -w
# $Id: plotlog,v 2.0 2002/09/22 02:10:16 tramm Exp $
#
# Invokes gnuplot on a log file
#

use strict;

open PLOT, "|gnuplot"
	or die "Unable to invokve gnuplot: $!\n";

my $file	= shift;
my $low		= shift || "";
my $high	= shift || "";

print PLOT <<"";
	set term png color
	set output "$file.png"
	plot								\\
		[] [$low:$high]						\\
		"$file" using 1 title "X acceleration"	with lines,	\\
		"" using 2 title "Y acceleration"	with lines,	\\
		"" using 3 title "Pitch rate"	with lines,	\\
		"" using 4 title "Roll rate"	with lines,	\\
		"" using 5 title "Yaw rate"	with lines
	quit

close PLOT

